apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1  # You can scale the number of replicas as needed
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: calculator-app:latest  # Replace with your image name
          imagePullPolicy: Never  # Prevents Kubernetes from pulling the image
          ports:
            - containerPort: 5000  # Exposing port 5000 for the Flask app

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app  # Ensure this matches the label in your Deployment
  ports:
    - protocol: TCP
      port: 5000  # Service will listen on port 5000
      targetPort: 5000  # Target port on the Flask app container
      nodePort: 30000  # Expose the service on node port 30000 (change as needed)
  type: NodePort  # Exposes the service externally via a NodePort

