apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1  # Number of pods you want to run
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: calculator-app:latest  # Replace with your image name and tag
        imagePullPolicy: Never  # Always pull the latest image
        ports:
        - containerPort: 5000  # Exposing port 5000 for the Flask app

